"""NeuroDiff CLI — Phases 1, 2, 3."""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Literal, Optional

import typer
from rich.console import Console

app = typer.Typer(
    name="neurodiff",
    help=(
        "🧠 NeuroDiff — Deep semantic git diff analysis for AI-generated code.\n\n"
        "Analyzes git diffs at AST level and runs multi-engine analysis:\n"
        "security, duplication, and architectural impact."
    ),
    rich_markup_mode="rich",
)

config_app = typer.Typer(help="Manage NeuroDiff configuration and API keys")
app.add_typer(config_app, name="config")

console = Console()

# Common types
_FormatType = Literal["terminal", "json", "html", "sarif", "all"]
_LangType = Literal["python", "javascript", "typescript", "auto"]
_OnlyType = Literal["semantic", "security", "duplication", "arch", "cognitive", "intent", "zeroday", "all"]


# ---------------------------------------------------------------------------
# index command
# ---------------------------------------------------------------------------

@app.command()
def index(
    repo_path: str = typer.Argument(".", help="Path to the Git repository to index"),
) -> None:
    """Index a repository for code duplication detection.

    Walks all Python/JS/TS files, extracts function bodies, and stores vector
    embeddings in a local ChromaDB. Run once before `neurodiff analyze`.
    """
    from neurodiff.core.ast_engine import ASTEngine
    from neurodiff.engines.duplication_engine import DuplicationEngine
    from neurodiff.core.semantic_events import NeuroDiffError

    try:
        repo_path_obj = Path(repo_path).resolve()
        console.print(f"[blue]Indexing repository:[/blue] {repo_path_obj}")

        ast_engine = ASTEngine()
        dup_engine = DuplicationEngine()

        if not dup_engine.has_chromadb:
            console.print(
                "[red]ChromaDB not available. Install with:[/red] "
                "pip install chromadb sentence-transformers"
            )
            raise typer.Exit(1)

        console.print("[yellow]Extracting and embedding functions…[/yellow]")
        count = dup_engine.index_repo(repo_path_obj, ast_engine)
        console.print(f"[green]Indexed [bold]{count}[/bold] functions successfully.[/green]")
        console.print(f"[dim]Database: {dup_engine.CHROMA_DB_PATH}[/dim]")

    except NeuroDiffError as e:
        console.print(f"[red]Error: {e}[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]Unexpected error: {e}[/red]")
        raise typer.Exit(1)


# ---------------------------------------------------------------------------
# init-arch-rules command
# ---------------------------------------------------------------------------

@app.command(name="init-arch-rules")
def init_arch_rules(
    output: str = typer.Option(
        "./arch-rules.yaml",
        "--output", "-o",
        help="Path to write the generated arch-rules.yaml",
    ),
    detect: bool = typer.Option(
        True,
        "--detect/--no-detect",
        help="Auto-detect project type (Django, FastAPI, plain Python)",
    ),
) -> None:
    """Generate a starter arch-rules.yaml for your project.

    NeuroDiff will auto-detect common project structures (Django, FastAPI,
    plain Python) and emit a tailored architecture rules file.
    """
    output_path = Path(output)

    project_type = "generic"
    if detect:
        cwd = Path.cwd()
        if (cwd / "manage.py").exists():
            project_type = "django"
        elif any(cwd.rglob("fastapi")):
            project_type = "fastapi"

    templates: dict[str, str] = {
        "django": _DJANGO_ARCH_RULES,
        "fastapi": _FASTAPI_ARCH_RULES,
        "generic": _GENERIC_ARCH_RULES,
    }

    content = templates.get(project_type, _GENERIC_ARCH_RULES)
    output_path.write_text(content, encoding="utf-8")

    console.print(f"[green]✓ Generated [bold]{output_path}[/bold] ({project_type} template)[/green]")
    console.print("[dim]Edit the file to match your project's layered architecture.[/dim]")


_GENERIC_ARCH_RULES = """\
# arch-rules.yaml — NeuroDiff Architectural Rules
# Generated by: neurodiff init-arch-rules

layers:
  - name: cli
    patterns: ["cli/*", "main.py"]
  - name: engines
    patterns: ["engines/*", "services/*"]
  - name: core
    patterns: ["core/*", "domain/*"]
  - name: output
    patterns: ["output/*", "views/*"]
  - name: models
    patterns: ["models/*", "*/semantic_events.py", "entities/*"]

forbidden_imports:
  - from: "core"
    to: "engines"
    reason: "Core must not depend on engines (DIP)"
  - from: "core"
    to: "cli"
    reason: "Core logic must not know about presentation"
  - from: "models"
    to: "core"
    reason: "Models must stay framework-agnostic"
"""

_DJANGO_ARCH_RULES = """\
# arch-rules.yaml — NeuroDiff Architectural Rules (Django)
# Generated by: neurodiff init-arch-rules --detect

layers:
  - name: views
    patterns: ["*/views.py", "*/views/*"]
  - name: serializers
    patterns: ["*/serializers.py", "*/serializers/*"]
  - name: services
    patterns: ["*/services.py", "*/services/*"]
  - name: models
    patterns: ["*/models.py", "*/models/*"]
  - name: utils
    patterns: ["*/utils.py", "*/utils/*"]

forbidden_imports:
  - from: "models"
    to: "views"
    reason: "Models must not import from views layer"
  - from: "models"
    to: "services"
    reason: "Models must not depend on service layer"
"""

_FASTAPI_ARCH_RULES = """\
# arch-rules.yaml — NeuroDiff Architectural Rules (FastAPI)
# Generated by: neurodiff init-arch-rules --detect

layers:
  - name: routers
    patterns: ["*/routers/*", "*/routes/*", "*/api/*"]
  - name: services
    patterns: ["*/services/*", "*/use_cases/*"]
  - name: repositories
    patterns: ["*/repositories/*", "*/db/*"]
  - name: schemas
    patterns: ["*/schemas/*", "*/models/*"]
  - name: core
    patterns: ["*/core/*", "*/config/*"]

forbidden_imports:
  - from: "schemas"
    to: "services"
    reason: "Schemas/DTOs must not depend on business logic"
  - from: "repositories"
    to: "routers"
    reason: "DB layer must not know about HTTP routing"
"""


# ---------------------------------------------------------------------------
# Config Commands
# ---------------------------------------------------------------------------
CONFIG_FILE = Path.home() / ".neurodiff" / "config.json"

@config_app.command("set-api-key")
def set_api_key(
    provider: str = typer.Argument(..., help="Provider name (gemini | claude | ollama)")
) -> None:
    """Securely save an API key for the LLM Engine."""
    provider = provider.lower()
    if provider not in ("gemini", "claude", "ollama"):
        console.print("[red]Error: Provider must be gemini, claude, or ollama[/red]")
        raise typer.Exit(1)

    # For ollama, it's a host URL not a key usually, but let's prompt anyway
    prompt_text = f"Enter API Key for {provider}" if provider != "ollama" else "Enter Ollama Host URL (e.g. http://localhost:11434)"
    api_key = typer.prompt(prompt_text, hide_input=(provider != "ollama"))
    
    config = {}
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                config = json.load(f)
        except json.JSONDecodeError:
            pass

    config[f"{provider}_key"] = api_key
    
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
    
    console.print(f"[green]✓ Saved configuration for {provider} in {CONFIG_FILE}[/green]")


# ---------------------------------------------------------------------------
# analyze command
# ---------------------------------------------------------------------------

@app.command()
def analyze(
    base_ref: str = typer.Argument(..., help="Base Git reference (commit, branch, tag)"),
    head_ref: str = typer.Argument(..., help="Head Git reference"),
    repo_path: str = typer.Option(".", "--repo-path", "-r", help="Path to Git repository"),
    format_type: _FormatType = typer.Option("terminal", "--format", "-f", help="Output format"),
    language: _LangType = typer.Option("auto", "--lang", "-l", help="Filter by language"),
    arch_rules: Optional[str] = typer.Option(
        None,
        "--arch-rules",
        help="Path to arch-rules.yaml (default: auto-discover in repo root)",
    ),
    only: Optional[_OnlyType] = typer.Option(
        None,
        "--only",
        help="Run only specific engine: semantic | security | duplication | arch | cognitive | intent | zeroday | all",
    ),
    use_llm: bool = typer.Option(False, "--llm", help="Run Phase 4 LLM deep analysis"),
    fail_on_mismatch: bool = typer.Option(False, "--fail-on-mismatch", help="Fail pipeline if intent vs reality verdict is mismatch or suspicious"),
    fail_on_critical_logic: bool = typer.Option(False, "--fail-on-critical-logic", help="Fail pipeline if any critical logic vulnerability is found"),
    llm_provider: Optional[str] = typer.Option(None, "--llm-provider", help="Force specific LLM provider: gemini | claude | ollama"),
    llm_delay: float = typer.Option(2.0, "--llm-delay", help="Seconds to delay between concurrent LLM calls"),
    llm_only: bool = typer.Option(False, "--llm-only", help="Skip static engines (assumes cached/mocked output if used in isolation, but standard run gathers data first)"),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Show verbose output (e.g., token usage)"),
    no_cache: bool = typer.Option(False, "--no-cache", help="Bypass LLM cache"),
    skip_security: bool = typer.Option(False, "--no-security", help="Skip security analysis"),
    skip_duplication: bool = typer.Option(False, "--no-duplication", help="Skip duplication"),
    skip_architecture: bool = typer.Option(False, "--no-architecture", help="Skip Phase 2 arch checks"),
    skip_arch_engine: bool = typer.Option(False, "--no-arch-engine", help="Skip Phase 3 arch engine"),
    skip_cognitive: bool = typer.Option(False, "--no-cognitive", help="Skip Phase 6 cognitive analysis"),
    # Phase 5 & 6 — CI/CD
    strict: bool = typer.Option(False, "--strict", help="Fail pipeline on HIGH severity findings (default: only CRITICAL)"),
    max_cfi: int = typer.Option(80, "--max-cfi", help="Fail pipeline if Cognitive Fatigue Index exceeds this threshold (Phase 6)"),
    sarif_output: Optional[str] = typer.Option(None, "--sarif-output", help="Write SARIF v2.1.0 report to this file path"),
    # Phase 7 — Dashboard & Active Corrections
    output_html: str = typer.Option("neurodiff-report.html", "--output", help="Path for HTML report"),
    open_browser: bool = typer.Option(False, "--open", help="Open HTML report in browser"),
    github_comment: bool = typer.Option(False, "--github-comment", help="Post PR comment via API"),
    repo_name: Optional[str] = typer.Option(None, "--repo", help="GitHub owner/repo (if not in Actions)"),
    pr_number: Optional[int] = typer.Option(None, "--pr", help="PR number (if not in Actions)"),
    corrections: bool = typer.Option(False, "--corrections", help="Generate active code corrections via LLM"),
    auto_fix: bool = typer.Option(False, "--auto-fix", help="Auto-apply HIGH confidence corrections"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show auto-fix changes without writing"),
    shadow: bool = typer.Option(False, "--shadow", help="Run Shadow Developer to generate/update docs"),
    # Feature 4 — Algorithm Performance Reviewer
    perf: bool = typer.Option(False, "--perf", help="Run Algorithm Performance Reviewer (AST + LLM)"),
    perf_limit: int = typer.Option(5, "--perf-limit", help="Maximum number of rewrites to generate (defaults to top 5)"),
    fail_on_slow: bool = typer.Option(False, "--fail-on-slow", help="Fail pipeline if O(n²) or worse pattern detected"),
    perf_write_benchmarks: bool = typer.Option(False, "--perf-write-benchmarks", help="Write perf_benchmark.py with runnable speedup proofs"),
    # Feature 5 — Collaborative PR Review Engine
    inline_comments: bool = typer.Option(False, "--inline-comments", help="Post inline PR comments"),
    platform: Optional[str] = typer.Option(None, "--platform", help="github | gitlab | bitbucket"),
    max_comments: int = typer.Option(10, "--max-comments", help="Max inline comments to post"),
) -> None:
    """Analyze semantic differences between two Git references.

    NeuroDiff runs four engines in sequence:

    \b
    Phase 1 — AST Engine:        functions/classes/imports changed
    Phase 2 — Security Engine:   secrets, injection patterns (semgrep optional)
    Phase 2 — Duplication:       ChromaDB RAG similarity (requires `neurodiff index`)
    Phase 3 — Arch Engine:       circular deps, layer violations, SOLID, blast radius

    Examples:

        neurodiff analyze HEAD~1 HEAD
        neurodiff analyze main feature/auth --format json
        neurodiff analyze v1.0 v2.0 --arch-rules ./arch-rules.yaml
        neurodiff analyze HEAD~1 HEAD --only arch
    """
    from neurodiff.core.ast_engine import ASTEngine
    from neurodiff.core.git_parser import GitParser
    from neurodiff.core.semantic_events import NeuroDiffError, FunctionAdded
    from neurodiff.engines.arch_engine import ArchEngine
    from neurodiff.engines.architecture_engine import ArchitectureEngine
    from neurodiff.engines.cognitive_engine import CognitiveEngine
    from neurodiff.engines.duplication_engine import DuplicationEngine
    from neurodiff.engines.llm_engine import ContextBuilder, get_provider, run_llm_analysis
    from neurodiff.engines.security_engine import SecurityEngine
    import asyncio
    import datetime

    if llm_only:
        use_llm = True

    # --only shortcut: disable everything except the requested engine
    if only and only != "all":
        skip_security = only != "security"
        skip_duplication = only != "duplication"
        skip_architecture = only not in ("arch",)
        skip_arch_engine = only not in ("arch", "cognitive")
        skip_cognitive = only != "cognitive"
        skip_intent = only != "intent"
        skip_zeroday = only != "zeroday"
    else:
        skip_intent = False
        skip_zeroday = False

    try:
        repo_path_obj = Path(repo_path).resolve()
        arch_rules_path = Path(arch_rules) if arch_rules else None

        console.print(
            f"[bold blue]🧠 NeuroDiff[/bold blue]  "
            f"[cyan]{base_ref}[/cyan]…[cyan]{head_ref}[/cyan]"
        )

        git_parser = GitParser(repo_path_obj)
        ast_engine = ASTEngine()

        security_engine = None if skip_security else SecurityEngine()
        dup_engine = None if skip_duplication else DuplicationEngine()
        arch2_engine = None if skip_architecture else ArchitectureEngine()
        arch3_engine = None if skip_arch_engine else ArchEngine(repo_path_obj, arch_rules_path)

        file_diffs = git_parser.get_file_diffs(base_ref, head_ref)
        if not file_diffs:
            console.print("[yellow]No changes found between the specified refs.[/yellow]")
            raise typer.Exit(0)

        all_events: list = []
        all_security: list = []
        all_duplication: list = []
        all_arch2: list = []
        added_func_bodies: list[tuple[FunctionAdded, str]] = []
        file_contents: dict[str, str] = {}

        for fd in file_diffs:
            if language != "auto" and fd.language != language:
                continue

            console.print(f"  [dim]→[/dim] [cyan]{fd.path}[/cyan]  [dim]({fd.language})[/dim]")

            if fd.content_after.strip():
                file_contents[fd.path] = fd.content_after

            # Phase 1 — AST
            events: list = []
            try:
                events = ast_engine.extract_events(
                    fd.content_before, fd.content_after, fd.language, fd.path
                )
                all_events.extend(events)
                for ev in events:
                    if isinstance(ev, FunctionAdded):
                        body = ast_engine._extract_function_body(
                            fd.content_after,
                            ev.start_line - 1,
                            ev.start_line + ev.body_lines - 2,
                        )
                        added_func_bodies.append((ev, body))
            except Exception as exc:
                console.print(f"    [yellow]⚠ AST: {exc}[/yellow]")

            # Phase 2 — Security
            if security_engine:
                try:
                    all_security.extend(security_engine.analyze(fd.content_after, fd.path, events))
                except Exception as exc:
                    console.print(f"    [yellow]⚠ Security: {exc}[/yellow]")

            # Phase 2 — Architecture heuristics (architecture_engine.py)
            if arch2_engine:
                try:
                    all_arch2.extend(arch2_engine.analyze(events, {fd.path: fd.content_after}))
                except Exception as exc:
                    console.print(f"    [yellow]⚠ Arch-2: {exc}[/yellow]")

        # Phase 2 — Duplication (across all files)
        all_dup_findings: list = []
        if dup_engine and added_func_bodies:
            if not dup_engine.has_chromadb:
                console.print(
                    "[yellow]⚠ Duplication skipped — ChromaDB unavailable. "
                    "Run [bold]neurodiff index .[/bold] first.[/yellow]"
                )
            else:
                try:
                    all_dup_findings = dup_engine.analyze(added_func_bodies)
                except Exception as exc:
                    console.print(f"[yellow]⚠ Duplication: {exc}[/yellow]")

        # Phase 3 — Arch Engine
        arch_report = None
        dependency_graph = None
        if arch3_engine:
            try:
                diff_files = [fd.path for fd in file_diffs]
                arch_report = arch3_engine.run(diff_files, all_events)
                dependency_graph = arch3_engine.graph
            except Exception as exc:
                console.print(f"[yellow]⚠ Arch engine: {exc}[/yellow]")

        # Phase 6 — Cognitive Engine
        cognitive_report = None
        if not skip_cognitive:
            try:
                cog_engine = CognitiveEngine()
                cognitive_report = cog_engine.run(
                    semantic_events=all_events,
                    file_diffs=file_diffs,
                    arch_report=arch_report,
                    dependency_graph=dependency_graph,
                )
            except Exception as exc:
                console.print(f"[yellow]⚠ Cognitive engine failed: {exc}[/yellow]")

        # Phase 4 — Logic Vulnerability (ZeroDay)
        zeroday_report = None
        if (use_llm or only == "zeroday") and not skip_zeroday:
            provider = get_provider(llm_provider, delay=llm_delay)
            if provider:
                from neurodiff.engines.zeroday_engine import ZeroDayEngine
                console.print(f"[cyan]Running Logic Vulnerability Analysis via {provider.name}…[/cyan]")
                zd_engine = ZeroDayEngine(provider)
                try:
                    zeroday_report = asyncio.run(zd_engine.run(all_events, file_diffs, all_security, arch_report))
                except Exception as exc:
                    console.print(f"[red]Zero-Day Engine Error: {exc}[/red]")

        # Phase 4 — Intent Verification
        intent_report = None
        if (use_llm or only == "intent") and not skip_intent:
            provider = get_provider(llm_provider, delay=llm_delay)
            if provider:
                from neurodiff.engines.intent_engine import extract_intent, build_semantic_summary, run_intent_analysis
                console.print(f"[cyan]Running Intent Verification via {provider.name}…[/cyan]")
                intent_obj = extract_intent(repo_path_obj, head_ref)
                semantic_summary = build_semantic_summary(all_events)
                try:
                    intent_report = asyncio.run(run_intent_analysis(intent_obj, semantic_summary, provider))
                except Exception as exc:
                    console.print(f"[red]Intent Engine Error: {exc}[/red]")

        # Phase 4 — LLM Deep Analysis
        llm_report = None
        if use_llm and only != "intent":
            provider = get_provider(llm_provider, delay=llm_delay)
            if not provider:
                console.print("[yellow]⚠ LLM Engine skipped: No valid provider configured (set ANTHROPIC_API_KEY, GOOGLE_API_KEY, or OLLAMA_HOST).[/yellow]")
            else:
                console.print(f"[cyan]Running LLM Analysis via {provider.name}…[/cyan]")
                repo_stats = {
                    "files_changed": len(file_diffs),
                    "total_events": len(all_events)
                }
                diff_metadata = {
                    "base_ref": base_ref,
                    "head_ref": head_ref,
                    "timestamp": datetime.datetime.now().isoformat()
                }
                
                llm_context = ContextBuilder.build(
                    events=all_events,
                    security=all_security,
                    duplication=all_dup_findings,
                    arch_report=arch_report,
                    repo_stats=repo_stats,
                    diff_metadata=diff_metadata,
                    cognitive_report=cognitive_report,
                    intent_report=intent_report,
                    zeroday_report=zeroday_report,
                )
                if verbose and llm_context.truncated:
                    console.print("[yellow]⚠ LLM context was truncated to fit the token limit.[/yellow]")
                
                try:
                    llm_report = asyncio.run(run_llm_analysis(llm_context, provider, use_cache=not no_cache))
                    if llm_report.error:
                        console.print(f"[red]LLM Engine Error: {llm_report.error}[/red]")
                except Exception as exc:
                    console.print(f"[red]LLM Engine critical failure: {exc}[/red]")

        # Phase 7 — Active Corrections
        global_context = None
        code_corrections = []
        if corrections and use_llm and provider:
            from neurodiff.engines.context_engine import ContextEngine
            from neurodiff.engines.correction_engine import CorrectionEngine, CorrectionRequest
            import asyncio
            
            console.print("[cyan]Building Global Context & Generating active corrections…[/cyan]")
            ctx_engine = ContextEngine(repo_path_obj)
            findings_to_query = all_security + getattr(arch_report, "circular_deps", []) + getattr(arch_report, "layer_violations", [])
            global_context = ctx_engine.build_context(
                dependency_graph=dependency_graph,
                layer_names=[layer.get("name") for layer in getattr(arch3_engine, "layer_config", {}).get("layers", [])] if arch3_engine else None,
                duplication_engine=dup_engine,
                findings_to_query=findings_to_query
            )
            
            requests = []
            for f in all_security:
                if getattr(f, "severity", "") in ["high", "critical"]:
                    req = CorrectionRequest(
                        finding_id=getattr(f, "rule_id", "security_issue"),
                        finding_type="security",
                        severity=getattr(f, "severity", "high"),
                        file_path=getattr(f, "file", "unknown"),
                        function_name=getattr(f, "function_name", None),
                        original_code=file_contents.get(getattr(f, "file", ""), ""),
                        finding_description=getattr(f, "description", ""),
                        global_context=global_context
                    )
                    requests.append(req)
                    
            corr_engine = CorrectionEngine(provider=provider)
            code_corrections = asyncio.run(corr_engine.generate_all_corrections(requests))
            
            if auto_fix or dry_run:
                from neurodiff.engines.correction_engine import apply_correction
                for corr in code_corrections:
                    if corr.confidence > 0.8:
                        if not auto_fix and dry_run:
                            apply_correction(corr, repo_path_obj, dry_run=True)
                            console.print(f"[yellow]Dry-run: Would apply patch for {corr.finding_id}[/yellow]")
                        elif auto_fix:
                            success = apply_correction(corr, repo_path_obj, dry_run=False)
                            if success:
                                console.print(f"[green]✓ Applied patch for {corr.finding_id}[/green]")
                            else:
                                console.print(f"[red]✗ Failed to apply patch for {corr.finding_id}[/red]")

        # Shadow Developer
        shadow_report = None
        if shadow and use_llm:
            provider = get_provider(llm_provider, delay=llm_delay)
            if provider:
                from neurodiff.engines.shadow_engine import ShadowEngine
                console.print("[cyan]Running Shadow Developer…[/cyan]")
                shadow_eng = ShadowEngine(provider=provider)
                shadow_inv = shadow_eng.scan_repo(repo_path_obj)
                shadow_eng.print_preview(repo_path_obj, shadow_inv, no_inline=False)
                try:
                    if shadow_inv.mode == "generate":
                        shadow_report = asyncio.run(shadow_eng.run_generate(
                            repo_path_obj, shadow_inv, dry_run=dry_run, arch_report=arch_report,
                        ))
                    else:
                        shadow_report = asyncio.run(shadow_eng.run_update(
                            repo_path_obj, shadow_inv, all_events, dry_run=dry_run,
                        ))
                except Exception as exc:
                    console.print(f"[red]Shadow Developer Error: {exc}[/red]")

        # Feature 4 — Algorithm Performance Reviewer
        perf_report = None
        if perf:
            from neurodiff.engines.perf_engine import PerfEngine
            perf_provider = get_provider(llm_provider, delay=llm_delay) if use_llm else None
            console.print("[cyan]Running Algorithm Performance Reviewer…[/cyan]")
            perf_eng = PerfEngine(provider=perf_provider)
            try:
                perf_report = asyncio.run(perf_eng.run(
                    all_events,
                    file_diffs,
                    write_benchmarks=perf_write_benchmarks,
                    repo_path=repo_path_obj,
                    rewrite_limit=perf_limit,
                ))
                if perf_report.findings:
                    console.print(
                        f"  [{'red' if perf_report.critical_count else 'yellow'}]"
                        f"Found {len(perf_report.findings)} performance issues "
                        f"({perf_report.critical_count} critical, {perf_report.high_count} high)[/{'red' if perf_report.critical_count else 'yellow'}]"
                    )
                else:
                    console.print("  [green]✓ No algorithmic performance issues found.[/green]")
                if perf_report.benchmark_file:
                    console.print(f"  [green]✓ Benchmark written to {perf_report.benchmark_file}[/green]")
            except Exception as exc:
                console.print(f"[red]Performance Reviewer Error: {exc}[/red]")

        console.print()

        if format_type == "json":
            _output_json(all_events, all_security, all_dup_findings, all_arch2, arch_report, llm_report, cognitive_report)
        elif format_type in ["terminal", "all"]:
            from neurodiff.output.reporter import Reporter
            reporter = Reporter(console)
            reporter.report(
                str(repo_path_obj),
                base_ref,
                head_ref,
                len(file_diffs),
                all_events,
                all_security,
                all_dup_findings,
                all_arch2,
                arch_report=arch_report,
                llm_report=llm_report,
                cognitive_report=cognitive_report,
                intent_report=intent_report,
                zeroday_report=zeroday_report,
                shadow_report=shadow_report,
                # pyrefly: ignore [unexpected-keyword]
                perf_report=perf_report,
                verbose=verbose,
            )

        if fail_on_mismatch and intent_report and intent_report.verdict in ("mismatch", "suspicious"):
            console.print(f"[bold red]Pipeline failed: Intent verification returned {intent_report.verdict}[/bold red]")
            raise typer.Exit(1)
            
        if fail_on_critical_logic and zeroday_report and zeroday_report.critical_count > 0:
            console.print(f"[bold red]Pipeline failed: Found {zeroday_report.critical_count} critical logic vulnerabilities[/bold red]")
            raise typer.Exit(1)

        if inline_comments:
            from neurodiff.integrations.inline_commenter import (
                map_findings_to_comments, detect_platform,
                post_github_review, post_gitlab_review, post_bitbucket_review
            )
            comments = map_findings_to_comments(all_security, zeroday_report, perf_report)
            if len(comments) > max_comments:
                console.print(f"[dim]Truncating comments from {len(comments)} to {max_comments}[/dim]")
                comments = comments[:max_comments]
            
            p = platform or detect_platform()
            if p == "github":
                # Need repo and PR number for GitHub (mocked or from env)
                repo = os.environ.get("GITHUB_REPOSITORY", "user/repo")
                pr_number_str = os.environ.get("GITHUB_REF", "").split("/")
                pr_number = int(pr_number_str[2]) if len(pr_number_str) > 2 and pr_number_str[1] == "pull" else 1
                token = os.environ.get("GITHUB_TOKEN", "")
                
                overall_risk = "CRITICAL" if (all_security and any(s.severity == "critical" for s in all_security)) or (zeroday_report and zeroday_report.critical_count > 0) else "COMMENT"
                asyncio.run(post_github_review(
                    comments, repo, pr_number, token, 
                    overall_risk,
                    file_diffs
                ))
            elif p == "gitlab":
                asyncio.run(post_gitlab_review(
                    comments, 
                    os.environ.get("CI_PROJECT_ID", ""),
                    os.environ.get("CI_MERGE_REQUEST_IID", ""),
                    os.environ.get("GITLAB_TOKEN", "")
                ))
            elif p == "bitbucket":
                asyncio.run(post_bitbucket_review(
                    comments,
                    os.environ.get("BITBUCKET_WORKSPACE", ""),
                    os.environ.get("BITBUCKET_REPO_SLUG", ""),
                    os.environ.get("BITBUCKET_PR_ID", ""),
                    os.environ.get("BITBUCKET_TOKEN", "")
                ))

        if fail_on_slow and perf_report and perf_report.critical_count > 0:
            console.print(f"[bold red]Pipeline failed: Found {perf_report.critical_count} O(n²)+ algorithmic patterns[/bold red]")
            raise typer.Exit(1)

        # Phase 5 — SARIF output
        if sarif_output or format_type == "all":
            from neurodiff.output.sarif_formatter import build_sarif
            import json as _json
            sarif_doc = build_sarif(all_security, all_dup_findings, arch_report)
            sarif_path = Path(sarif_output if sarif_output else "neurodiff-report.sarif")
            sarif_path.write_text(_json.dumps(sarif_doc, indent=2), encoding="utf-8")
            console.print(f"[green]✓ SARIF report written to {sarif_path}[/green]")

        # Phase 7 — HTML Report
        if format_type in ["html", "all"]:
            from neurodiff.output.html_reporter import generate_html, FullReport
            import time
            full_report = FullReport(
                metadata={
                    "repo": repo_path_obj.name,
                    "base_ref": base_ref,
                    "head_ref": head_ref,
                    "duration_s": 1.0,
                },
                semantic_events=all_events,
                security=all_security,
                duplication=all_dup_findings,
                arch=arch_report,
                cognitive=cognitive_report,
                llm=llm_report,
                intent_report=intent_report,
                zeroday_report=zeroday_report,
                shadow_report=shadow_report,
                global_context=global_context,
                corrections=code_corrections
            )
            html_content = generate_html(full_report)
            Path(output_html).write_text(html_content, encoding="utf-8")
            console.print(f"[green]✓ HTML report written to {output_html}[/green]")
            
            if open_browser:
                import webbrowser
                webbrowser.open(str(Path(output_html).resolve()))

        # Phase 7 — GitHub PR comment
        if github_comment:
            from neurodiff.output.github_commenter import post_pr_comment, get_pr_number, get_repo
            import os
            import asyncio
            
            gh_token = os.environ.get("GITHUB_TOKEN", "")
            final_repo = repo_name or get_repo()
            final_pr = pr_number or get_pr_number()
            
            if not final_repo or not final_pr:
                console.print("[yellow]⚠ --github-comment skipped: Could not determine repo or PR number.[/yellow]")
            else:
                from neurodiff.output.html_reporter import FullReport
                report_payload = FullReport(
                    metadata={
                        "repo": repo_path_obj.name,
                        "base_ref": base_ref,
                        "head_ref": head_ref,
                        "duration_s": 1.0,
                    },
                    semantic_events=all_events,
                    security=all_security,
                    duplication=all_dup_findings,
                    arch=arch_report,
                    cognitive=cognitive_report,
                    llm=llm_report,
                    intent_report=intent_report,
                    zeroday_report=zeroday_report,
                    shadow_report=shadow_report,
                    global_context=global_context,
                    corrections=code_corrections
                )
                
                async def _post_comment() -> None:
                    ok = await post_pr_comment(report_payload, gh_token, final_repo, final_pr)
                    if ok:
                        console.print(f"[green]✓ NeuroDiff comment posted/updated in PR #{final_pr}[/green]")
                    else:
                        console.print(f"[red]✗ Failed to post PR comment (check token / permissions).[/red]")
                asyncio.run(_post_comment())

        # Phase 5 — Exit codes
        is_safe = _compute_is_safe(all_security, arch_report, llm_report, cognitive_report, strict, max_cfi)
        if not is_safe:
            raise typer.Exit(1)


    except typer.Exit:
        raise
    except NeuroDiffError as e:
        console.print(f"[red]Error: {e}[/red]")
        raise typer.Exit(1)
    except Exception as e:
        console.print(f"[red]Unexpected error: {e}[/red]")
        raise typer.Exit(1)


# ---------------------------------------------------------------------------
# Exit code helper (Phase 5)
# ---------------------------------------------------------------------------

def _compute_is_safe(
    security_findings: list,
    arch_report: Any,
    llm_report: Any,
    cognitive_report: Any | None = None,
    strict: bool = False,
    max_cfi: int = 80,
) -> bool:
    """Determine if the diff is safe to merge for CI/CD exit code purposes."""
    if cognitive_report and cognitive_report.fatigue_index.total_score > max_cfi:
        return False

    # If LLM ran, trust its judgment exclusively
    if llm_report is not None and not llm_report.error:
        es = llm_report.executive_summary
        if isinstance(es, dict) and "safe_to_merge" in es:
            return bool(es["safe_to_merge"])

    # No LLM: use static severity threshold
    fail_severities = {"critical", "high"} if strict else {"critical"}
    for f in security_findings:
        if getattr(f, "severity", "").lower() in fail_severities:
            return False
    if arch_report:
        for f in arch_report.circular_deps + arch_report.layer_violations:
            if getattr(f, "severity", "").lower() in fail_severities:
                return False
    return True


# ---------------------------------------------------------------------------
# JSON output helper
# ---------------------------------------------------------------------------

def _output_json(
    semantic_events: list,
    security_findings: list,
    duplication_findings: list,
    architecture_findings: list,
    arch_report,
    llm_report = None,
    cognitive_report = None,
) -> None:
    from neurodiff.core.semantic_events import (
        ClassAdded, ClassModified,
        FunctionAdded, FunctionModified, FunctionRemoved,
        ImportAdded, ImportRemoved,
    )

    def event_to_dict(e) -> dict:
        if isinstance(e, FunctionAdded):
            return {
                "type": "FunctionAdded", "name": e.name, "file": e.file,
                "start_line": e.start_line, "body_lines": e.body_lines,
                "calls": e.calls, "cyclomatic_complexity": e.cyclomatic_complexity,
            }
        if isinstance(e, FunctionModified):
            return {
                "type": "FunctionModified", "name": e.name, "file": e.file,
                "start_line": e.start_line, "lines_before": e.lines_before,
                "lines_after": e.lines_after, "signature_changed": e.signature_changed,
                "calls_added": e.calls_added, "calls_removed": e.calls_removed,
                "complexity_before": e.complexity_before, "complexity_after": e.complexity_after,
            }
        if isinstance(e, FunctionRemoved):
            return {"type": "FunctionRemoved", "name": e.name, "file": e.file}
        if isinstance(e, ClassAdded):
            return {
                "type": "ClassAdded", "name": e.name, "file": e.file,
                "methods": e.methods, "inherits_from": e.inherits_from,
            }
        if isinstance(e, ClassModified):
            return {
                "type": "ClassModified", "name": e.name, "file": e.file,
                "methods_added": e.methods_added, "methods_removed": e.methods_removed,
            }
        if isinstance(e, ImportAdded):
            return {"type": "ImportAdded", "module": e.module, "file": e.file, "symbols": e.symbols}
        if isinstance(e, ImportRemoved):
            return {"type": "ImportRemoved", "module": e.module, "file": e.file}
        return {}

    output: dict = {
        "semantic_events": [event_to_dict(e) for e in semantic_events],
        "security_findings": [
            {
                "rule_id": f.rule_id, "category": f.category,
                "description": f.description, "severity": f.severity,
                "file": f.file, "line": f.line, "function_name": f.function_name,
            }
            for f in security_findings
        ],
        "duplication_findings": [
            {
                "new_function": f.new_function, "new_file": f.new_file,
                "similar_function": f.similar_function, "similar_file": f.similar_file,
                "similarity_score": round(f.similarity_score, 4), "severity": f.severity,
            }
            for f in duplication_findings
        ],
        "architecture_findings": [
            {
                "rule_id": f.rule_id, "title": f.title, "description": f.description,
                "severity": f.severity, "file": f.file, "entity_name": f.entity_name,
                "suggestion": f.suggestion,
            }
            for f in architecture_findings
        ],
    }

    if arch_report is not None:
        output["arch_report"] = {
            "layer_violations": [
                {"severity": f.severity, "category": f.category, "file": f.file,
                 "description": f.description, "involved_modules": f.involved_modules}
                for f in arch_report.layer_violations
            ],
            "circular_deps": [
                {"severity": f.severity, "description": f.description,
                 "involved_modules": f.involved_modules}
                for f in arch_report.circular_deps
            ],
            "solid_findings": [
                {"principle": f.principle, "severity": f.severity, "file": f.file,
                 "entity": f.entity, "description": f.description}
                for f in arch_report.solid_findings
            ],
            "blast_radius": arch_report.blast_radius,
        }

    if cognitive_report is not None:
        from dataclasses import asdict
        try:
            output["cognitive_report"] = asdict(cognitive_report)
        except Exception:
            output["cognitive_report"] = "Error serializing cognitive report"

    if llm_report is not None:
        output["llm_report"] = {
            "provider": llm_report.provider_used,
            "executive_summary": llm_report.executive_summary,
            "pattern_analysis": llm_report.pattern_analysis,
            "fix_plan": llm_report.fix_plan,
            "error": llm_report.error,
        }

    console.print(json.dumps(output, indent=2))


# ---------------------------------------------------------------------------
# shadow command (standalone)
# ---------------------------------------------------------------------------
@app.command()
def shadow(
    repo_path: str = typer.Argument(".", help="Path to the repository"),
    force_generate: bool = typer.Option(False, "--force-generate", help="Force GENERATE mode even if docs exist"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show preview without writing files"),
    no_inline: bool = typer.Option(False, "--no-inline", help="Skip inline docstring insertion (only .md files)"),
    llm_provider: Optional[str] = typer.Option(None, "--llm-provider", help="Force LLM provider: gemini | claude | ollama"),
    llm_delay: float = typer.Option(2.0, "--llm-delay", help="Seconds to delay between LLM calls"),
) -> None:
    """Shadow Developer — auto-generate or update project documentation.

    \b
    Modes:
      GENERATE  Creates README.md, ARCHITECTURE.md, docs/api.md, and inserts docstrings.
      UPDATE    Detects function/class signature changes and patches existing docs.

    \b
    Examples:
      neurodiff shadow .                  # Auto-detect mode
      neurodiff shadow . --force-generate # Force full generation
      neurodiff shadow . --dry-run        # Preview without writing
      neurodiff shadow . --no-inline      # Only generate .md files
    """
    import asyncio
    from neurodiff.engines.shadow_engine import ShadowEngine, ShadowReport
    from neurodiff.engines.llm_engine import get_provider

    repo_path_obj = Path(repo_path).resolve()
    if not repo_path_obj.exists():
        console.print(f"[red]Repository path not found: {repo_path_obj}[/red]")
        raise typer.Exit(1)

    provider = get_provider(llm_provider, delay=llm_delay)
    if not provider:
        console.print("[red]No LLM provider configured. Set GOOGLE_API_KEY, ANTHROPIC_API_KEY, or OLLAMA_HOST.[/red]")
        raise typer.Exit(1)

    engine = ShadowEngine(provider=provider)

    console.print("[blue]Scanning repository documentation state…[/blue]")
    inventory = engine.scan_repo(repo_path_obj)

    if force_generate:
        inventory.mode = "generate"

    engine.print_preview(repo_path_obj, inventory, no_inline=no_inline)

    if not dry_run:
        if not typer.confirm("Write these files?", default=False):
            console.print("[yellow]Aborted.[/yellow]")
            raise typer.Exit(0)

    try:
        if inventory.mode == "generate":
            report = asyncio.run(engine.run_generate(
                repo_path_obj, inventory,
                dry_run=dry_run, no_inline=no_inline,
            ))
        else:
            # Update mode — no diff events in standalone, just scan existing docs
            report = asyncio.run(engine.run_update(
                repo_path_obj, inventory, events=[], dry_run=dry_run,
            ))
    except Exception as exc:
        console.print(f"[red]Shadow Developer failed: {exc}[/red]")
        raise typer.Exit(1)

    # Print report
    _print_shadow_cli_report(report)


def _print_shadow_cli_report(report: Any) -> None:
    """Print a standalone Shadow Developer report to the terminal."""
    console.print(f"\n[bold magenta]━━━ 📝 Shadow Developer ━━━━━━━━━━━━━━━━━━[/bold magenta]")
    console.print(f"\nMode: [bold]{report.mode.upper()}[/bold]")

    if report.error:
        console.print(f"[red]Error: {report.error}[/red]")
        return

    if report.files_generated:
        console.print("\n[bold]Generated:[/bold]")
        for f in report.files_generated:
            console.print(f"  [green]✅[/green] {f}")

    if report.files_updated:
        console.print("\n[bold]Updated:[/bold]")
        for f in report.files_updated:
            console.print(f"  [green]✅[/green] {f}")

    if report.docstrings_added:
        console.print(f"\n[bold]Docstrings added:[/bold] {report.docstrings_added}")
    if report.docstrings_updated:
        console.print(f"[bold]Docstrings updated:[/bold] {report.docstrings_updated}")
    if report.functions_still_undocumented:
        console.print(f"[yellow]⚠️  Functions still undocumented:[/yellow] {report.functions_still_undocumented}")

    console.print(f"\n[bold]Coverage:[/bold] {report.coverage_before:.1f}% → {report.coverage_after:.1f}%")
    console.print()


# ---------------------------------------------------------------------------
# perf command (standalone — analyzes entire codebase, not just a diff)
# ---------------------------------------------------------------------------
@app.command()
def perf(
    repo_path: str = typer.Argument(".", help="Path to the repository"),
    only_changed: bool = typer.Option(False, "--only-changed", help="Only analyze functions modified in the last commit"),
    write_benchmarks: bool = typer.Option(False, "--write-benchmarks", help="Write perf_benchmark.py"),
    fail_on_slow: bool = typer.Option(False, "--fail-on-slow", help="Exit 1 if O(n²)+ patterns found"),
    perf_limit: int = typer.Option(5, "--perf-limit", help="Maximum number of rewrites to generate"),
    llm_provider: Optional[str] = typer.Option(None, "--llm-provider", help="gemini | claude | ollama"),
    llm_delay: float = typer.Option(2.0, "--llm-delay"),
    use_llm: bool = typer.Option(False, "--llm", help="Generate optimized rewrites via LLM"),
) -> None:
    """Algorithm Performance Reviewer — find and fix O(n²)+ patterns.

    \b
    Examples:
      neurodiff perf .                          # Scan whole repo (AST only)
      neurodiff perf . --llm                    # AST + LLM rewrites
      neurodiff perf . --llm --write-benchmarks # + runnable speedup proofs
      neurodiff perf . --fail-on-slow           # CI gate: fail on O(n²)
    """
    import asyncio
    from neurodiff.engines.perf_engine import PerfEngine, analyze_function, AlgorithmFinding
    from neurodiff.engines.llm_engine import get_provider

    repo_path_obj = Path(repo_path).resolve()
    if not repo_path_obj.exists():
        console.print(f"[red]Path not found: {repo_path_obj}[/red]")
        raise typer.Exit(1)

    provider = get_provider(llm_provider, delay=llm_delay) if use_llm else None

    # Walk all .py files and collect findings
    console.print("[blue]Scanning Python files for performance issues…[/blue]")
    all_findings: list[AlgorithmFinding] = []
    files_scanned = 0

    skip_dirs = {".git", "venv", ".venv", "__pycache__", ".tox", "dist", "build"}
    for py_file in sorted(repo_path_obj.rglob("*.py")):
        if set(py_file.parts) & skip_dirs:
            continue
        files_scanned += 1
        try:
            source = py_file.read_text(encoding="utf-8", errors="replace")
            found = analyze_function(source, func_name="", file_path=str(py_file.relative_to(repo_path_obj)))
            all_findings.extend(found)
        except Exception:
            pass

    console.print(f"  Scanned {files_scanned} files — found [bold]{len(all_findings)}[/bold] performance issues")

    if not all_findings:
        console.print("[green]✓ No algorithmic performance issues detected.[/green]")
        return

    # Print findings table
    from rich.table import Table
    t = Table(title="Performance Findings", show_lines=True)
    t.add_column("Severity", style="bold", width=10)
    t.add_column("Pattern", width=30)
    t.add_column("Function", width=25)
    t.add_column("File", width=40)
    t.add_column("Before → After", width=22)

    severity_colors = {"critical": "red", "high": "yellow", "medium": "cyan", "low": "dim"}
    for f in sorted(all_findings, key=lambda x: {"critical": 0, "high": 1, "medium": 2, "low": 3}[x.severity]):
        col = severity_colors.get(f.severity, "white")
        t.add_row(
            f"[{col}]{f.severity.upper()}[/{col}]",
            f.pattern_type,
            f.function_name,
            f.file,
            f"{f.complexity_before} → {f.complexity_after}",
        )
    console.print(t)

    # LLM rewrites
    if provider and all_findings:
        console.print(f"\n[cyan]Generating optimized rewrites via {provider.name}…[/cyan]")
        from neurodiff.engines.perf_engine import PerfEngine, BenchmarkGenerator
        eng = PerfEngine(provider=provider)
        # Use a dummy report structure to reuse the async rewrite logic
        from neurodiff.engines.perf_engine import _rewrite_one, PerfReport

        async def _run_rewrites():
            sem = asyncio.Semaphore(3)
            # Sort findings by severity (critical first)
            severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
            top_findings = sorted(all_findings, key=lambda f: severity_order.get(f.severity, 4))
            if perf_limit > 0:
                top_findings = top_findings[:perf_limit]

            # pyrefly: ignore [bad-argument-type]
            tasks = [_rewrite_one(f, provider, sem) for f in top_findings]
            return await asyncio.gather(*tasks, return_exceptions=True)

        results = asyncio.run(_run_rewrites())
        rewrites = [r for r in results if not isinstance(r, (Exception, type(None)))]

        for rw in rewrites:
            console.print(f"\n[bold magenta]⚡ {rw.finding.function_name}[/bold magenta] — {rw.finding.complexity_before} → {rw.finding.complexity_after}")
            console.print(f"  [dim]Why slow:[/dim] {rw.why_slow}")
            console.print(f"  [dim]Why fast:[/dim] {rw.why_fast}")
            console.print(f"  [dim]Big O proof:[/dim] {rw.big_o_proof}")
            console.print(f"  [green]Estimated speedup:[/green] {rw.estimated_speedup}")
            console.print(f"  Semantic equivalence: [bold]{rw.semantic_equivalence}[/bold]")

        if write_benchmarks and rewrites:
            bench_path = repo_path_obj / "perf_benchmark.py"
            BenchmarkGenerator.generate(rewrites, bench_path)
            console.print(f"\n[green]✓ Benchmark written to {bench_path}[/green]")
            console.print("[dim]  Run with: python perf_benchmark.py[/dim]")

    if fail_on_slow:
        critical = sum(1 for f in all_findings if f.severity == "critical")


        if critical:
            console.print(f"\n[bold red]Pipeline failed: {critical} O(n²)+ patterns detected[/bold red]")
            raise typer.Exit(1)


# ---------------------------------------------------------------------------
# Apply command (Phase 7)
# ---------------------------------------------------------------------------
@app.command()
def apply(
    finding_id: str = typer.Option(..., "--finding-id", help="ID of the finding to apply correction for"),
    repo_path: str = typer.Option(".", "--repo-path", "-r", help="Path to Git repository"),
) -> None:
    """Apply a downloaded .patch for a specific finding."""
    patch_file = Path(f"{finding_id}.patch")
    if not patch_file.exists():
        console.print(f"[red]Patch file {patch_file} not found in current directory.[/red]")
        raise typer.Exit(1)
        
    import subprocess
    cmd = ["git", "apply", str(patch_file)]
    result = subprocess.run(cmd, cwd=str(Path(repo_path).resolve()), capture_output=True, text=True, encoding="utf-8", errors="replace")
    if result.returncode == 0:
        console.print(f"[green]✓ Applied correction for {finding_id}[/green]")
    else:
        console.print(f"[red]✗ Failed to apply correction for {finding_id}: {result.stderr}[/red]")




bot_app = typer.Typer(help="Conversational PR bot commands")
app.add_typer(bot_app, name="bot")

@bot_app.command("respond")
def bot_respond() -> None:
    """Handle incoming webhook payload from CI environment."""
    from neurodiff.integrations.conversation_handler import parse_webhook_payload
    payload_str = os.environ.get("NEURODIFF_PAYLOAD", "{}")
    import json
    payload = json.loads(payload_str)
    
    comment = parse_webhook_payload(payload)
    if not comment:
        console.print("[dim]No NeuroDiff command found in payload.[/dim]")
        return
        
    console.print(f"[green]Detected command from {comment.author}: {comment.body}[/green]")
    # Would route to COMMANDS and provider here...
    
@bot_app.command("serve")
def bot_serve(port: int = typer.Option(8080, "--port")) -> None:
    """Start local webhook server for testing."""
    import http.server
    import socketserver
    
    class WebhookHandler(http.server.BaseHTTPRequestHandler):
        def do_POST(self):
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"OK")
            
    with socketserver.TCPServer(("", port), WebhookHandler) as httpd:
        console.print(f"Serving at port {port}")
        httpd.serve_forever()
        
@bot_app.command("test")
def bot_test(finding_id: str = typer.Option(...), command: str = typer.Option(...)) -> None:
    """Test conversation locally."""
    console.print(f"Testing command '{command}' on finding '{finding_id}'...")

if __name__ == "__main__":
    app()
