"""GitHub API integration for posting PR comments and checking run status.

Reads from standard GitHub Actions environment variables:
  - GITHUB_TOKEN       (required)
  - GITHUB_REPOSITORY  (e.g. "owner/repo")
  - GITHUB_REF         (e.g. "refs/pull/42/merge")
  - GITHUB_SHA         (current commit SHA)
"""
from __future__ import annotations

import os
import re
import logging
from typing import Any

logger = logging.getLogger(__name__)

_GITHUB_API = "https://api.github.com"


def _get_pr_number(github_ref: str) -> int | None:
    """Extract PR number from refs/pull/{N}/merge."""
    match = re.search(r"refs/pull/(\d+)/", github_ref)
    if match:
        return int(match.group(1))
    return None


class GitHubClient:
    """Thin async-capable client for GitHub REST API v3."""

    def __init__(
        self,
        token: str,
        repository: str,
        timeout: int = 20,
    ):
        self.token = token
        self.repository = repository
        self.timeout = timeout

    def _headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        }

    async def post_pr_comment(self, pr_number: int, body: str) -> bool:
        """Post a comment on a Pull Request. Returns True on success."""
        try:
            import httpx
            url = f"{_GITHUB_API}/repos/{self.repository}/issues/{pr_number}/comments"
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                resp = await client.post(url, headers=self._headers(), json={"body": body})
                if resp.status_code in (200, 201):
                    logger.info(f"PR comment posted to #{pr_number}")
                    return True
                else:
                    logger.warning(f"GitHub API error {resp.status_code}: {resp.text}")
                    return False
        except Exception as exc:
            logger.error(f"Failed to post PR comment: {exc}")
            return False

    async def delete_previous_neurodiff_comments(self, pr_number: int) -> None:
        """Delete old NeuroDiff comments to keep the PR clean (only latest comment shown)."""
        try:
            import httpx
            url = f"{_GITHUB_API}/repos/{self.repository}/issues/{pr_number}/comments"
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                resp = await client.get(url, headers=self._headers(), params={"per_page": 100})
                if resp.status_code != 200:
                    return
                comments = resp.json()
                for comment in comments:
                    body: str = comment.get("body", "")
                    # Identify our own comments by their footer
                    if "Generated by [NeuroDiff]" in body:
                        del_url = f"{_GITHUB_API}/repos/{self.repository}/issues/comments/{comment['id']}"
                        await client.delete(del_url, headers=self._headers())
        except Exception as exc:
            logger.warning(f"Could not clean old PR comments: {exc}")


def get_github_client_from_env() -> GitHubClient | None:
    """Build a GitHubClient from environment variables (used inside GitHub Actions)."""
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("NEURODIFF_GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo:
        return None
    return GitHubClient(token=token, repository=repo)


def get_pr_number_from_env() -> int | None:
    """Return PR number from the GITHUB_REF env var set by GitHub Actions."""
    ref = os.environ.get("GITHUB_REF", "")
    return _get_pr_number(ref)
