"""Phase 7 — GitHub Commenter.

Posts structured analysis results as a GitHub PR comment via the GitHub REST API.
"""
from __future__ import annotations

import logging
import os
import re
from typing import Any

from neurodiff.output.html_reporter import FullReport

logger = logging.getLogger(__name__)

# Must match the hidden marker to allow updating previous comments
COMMENT_MARKER = "<!-- neurodiff-report -->"
VERSION = "0.7.0"

def get_pr_number() -> int | None:
    """Auto-detect PR context from GitHub Actions."""
    ref = os.environ.get("GITHUB_REF", "")
    match = re.search(r'refs/pull/(\d+)/merge', ref)
    if match:
        return int(match.group(1))
    
    # Try GITHUB_EVENT_PATH fallback if needed, but standard is GITHUB_REF
    return None

def get_repo() -> str | None:
    """Auto-detect repo from GitHub Actions."""
    return os.environ.get("GITHUB_REPOSITORY")

def render_github_markdown(report: FullReport) -> str:
    """Renders the FullReport to a GitHub-flavored Markdown string."""
    
    # Process Metrics
    num_crit_sec = sum(1 for f in report.security if getattr(f, "severity", "") == "critical")
    num_med_sec = sum(1 for f in report.security if getattr(f, "severity", "") == "medium")
    sec_issues = f"{num_crit_sec} critical, {num_med_sec} medium" if report.security else "No issues"
    sec_icon = "⚠️ Issues found" if report.security else "✅ Pass"
    
    num_high_dup = sum(1 for f in report.duplication if getattr(f, "similarity_score", 0) > 0.9)
    dup_issues = f"{num_high_dup} pairs >90% similar" if num_high_dup > 0 else "No warnings"
    dup_icon = "⚠️ Warning" if num_high_dup > 0 else "✅ Pass"
    
    num_arch = len(getattr(report.arch, "layer_violations", []))
    num_circ = len(getattr(report.arch, "circular_deps", []))
    arch_issues = f"{num_circ} circular dep, {num_arch} layer violations" if (num_circ or num_arch) else "No violations"
    arch_icon = "❌ Violations" if (num_circ or num_arch) else "✅ Pass"
    
    cfi = report.cognitive.fatigue_index if report.cognitive else None
    cfi_score = getattr(cfi, "total_score", 0) if cfi else 0
    cfi_grade = getattr(cfi, "grade", "A") if cfi else "A"
    review_time = getattr(cfi, "review_time_estimate", "~15 min") if cfi else "~15 min"
    reviewers = getattr(cfi, "reviewer_recommendation", "1 reviewer") if cfi else "1 reviewer"
    
    ai_prob = report.cognitive.ai_generated.probability if report.cognitive else 0
    patterns = getattr(report.cognitive.commit_patterns, "anti_patterns", []) if report.cognitive else []
    
    overall = getattr(report.cognitive, "overall_verdict", "safe").upper()
    overall_icon = "⚠️" if overall != "SAFE" else "✅"
    
    head_ref = report.metadata.get("head_ref", "HEAD")
    base_ref = report.metadata.get("base_ref", "HEAD~1")
    
    lines = []
    lines.append(f"## 🔍 NeuroDiff Analysis — `{base_ref} → {head_ref}`\n")
    lines.append(f"> **Overall Risk: {overall_icon} {overall}** | Generated by [NeuroDiff](https://github.com/user/neurodiff)\n")
    lines.append(COMMENT_MARKER)
    lines.append("\n### 📊 Summary\n")
    lines.append("| Engine | Status | Findings |")
    lines.append("|--------|--------|----------|")
    lines.append(f"| 🛡️ Security | {sec_icon} | {sec_issues} |")
    lines.append(f"| 🔁 Duplication | {dup_icon} | {dup_issues} |")
    lines.append(f"| 🏗️ Architecture | {arch_icon} | {arch_issues} |")
    lines.append(f"| 🧠 Cognitive Load | ⚠️ Grade {cfi_grade} | CFI: {cfi_score}/100, {review_time} review |")
    lines.append("\n### 🔴 Critical Findings\n")
    
    for f in report.security:
        if getattr(f, "severity", "") == "critical":
            lines.append(f"**[SECURITY]** `{getattr(f, 'file', 'unknown')}:{getattr(f, 'line', 0)}` — {getattr(f, 'description', 'Issue')}")
    
    if num_circ:
        lines.append(f"**[ARCH]** Circular dependency: `{report.arch.circular_deps[0]}`")
        
    if not lines[-1].startswith("**["):
        lines.append("*No critical findings detected.*")
        
    lines.append("\n### 🧠 Cognitive Load\n")
    lines.append(f"- **AI-Generated Code Probability:** {ai_prob:.0%}")
    lines.append(f"- **Review Time Estimate:** {review_time} | **Recommended Reviewers:** {reviewers}")
    if patterns:
        ap_strs = [f"{p.name} {'🔴' if p.severity == 'high' else '🟡'}" for p in patterns]
        lines.append(f"- **Anti-patterns:** {', '.join(ap_strs)}")
    
    if overall == "DANGER" or num_crit_sec > 0 or num_circ > 0:
        lines.append("\n### ✅ Merge Recommendation\n")
        lines.append("> ⛔ **NOT SAFE TO MERGE** — Resolve critical findings first.\n")
        lines.append("<details>")
        lines.append("<summary>📋 Before-Merge Checklist</summary>\n")
        if num_circ:
            lines.append("- [ ] Resolve circular dependencies")
        if num_crit_sec > 0:
            lines.append("- [ ] Remove security vulnerabilities")
        if report.corrections:
            lines.append(f"- [ ] Review {len(report.corrections)} active corrections generated")
        lines.append("\n</details>")
        
    lines.append("\n---\n")
    lines.append(f"<sub>🤖 NeuroDiff v{VERSION} | Engines: ast, security, duplication, arch, cognitive, context, llm, corrections</sub>")
    
    return "\n".join(lines)


async def post_pr_comment(report: FullReport, token: str, repo: str, pr_number: int) -> bool:
    """Posts or updates a GitHub PR comment."""
    if not token:
        logger.warning("No GITHUB_TOKEN provided; skipping PR comment.")
        return False
        
    try:
        import httpx
    except ImportError:
        logger.warning("httpx not installed. Cannot post to GitHub.")
        return False

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": f"NeuroDiff/{VERSION}"
    }
    
    body = render_github_markdown(report)
    
    async with httpx.AsyncClient() as client:
        # First, try to find an existing comment
        try:
            resp = await client.get(url, headers=headers)
            if resp.status_code == 200:
                comments = resp.json()
                for comment in comments:
                    if COMMENT_MARKER in str(comment.get("body", "")):
                        # Found existing comment, PATCH it
                        comment_url = comment.get("url")
                        patch_resp = await client.patch(comment_url, json={"body": body}, headers=headers)
                        return patch_resp.status_code == 200
        except Exception as e:
            logger.error(f"Error fetching existing comments: {e}")
            
        # If not found or error, POST a new one
        try:
            post_resp = await client.post(url, json={"body": body}, headers=headers)
            return post_resp.status_code == 201
        except Exception as e:
            logger.error(f"Error posting new comment: {e}")
            return False
